//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIONINFO> ACTIONINFO { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<R_DEPARTMENT_ACTIONINFO> R_DEPARTMENT_ACTIONINFO { get; set; }
        public virtual DbSet<R_ROLEINFO_ACTIONINFO> R_ROLEINFO_ACTIONINFO { get; set; }
        public virtual DbSet<R_USERINFO_ACTIONINFO> R_USERINFO_ACTIONINFO { get; set; }
        public virtual DbSet<R_USERINFO_DEPARTMENT> R_USERINFO_DEPARTMENT { get; set; }
        public virtual DbSet<R_USERINFO_ROLEINFO> R_USERINFO_ROLEINFO { get; set; }
        public virtual DbSet<ROLEINFO> ROLEINFO { get; set; }
        public virtual DbSet<USERINFO> USERINFO { get; set; }
    }
}
