//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_USERINFO_ACTIONINFO
    {
        public decimal ID { get; set; }
        public decimal USERINFOID { get; set; }
        public decimal ACTIONINFOID { get; set; }
        public Nullable<decimal> ISPASS { get; set; }
    
        public virtual ACTIONINFO ACTIONINFO { get; set; }
        public virtual USERINFO USERINFO { get; set; }
    }
}
