//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLEINFO
    {
        public decimal ID { get; set; }
        public string ROLENAME { get; set; }
        public Nullable<decimal> DELFLAG { get; set; }
        public Nullable<System.DateTime> SUBTIME { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
        public string SORT { get; set; }
    }
}
