//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERINFO()
        {
            this.R_USERINFO_ACTIONINFO = new HashSet<R_USERINFO_ACTIONINFO>();
            this.R_USERINFO_DEPARTMENT = new HashSet<R_USERINFO_DEPARTMENT>();
            this.R_USERINFO_ROLEINFO = new HashSet<R_USERINFO_ROLEINFO>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public string UNAME { get; set; }
        public string UPWD { get; set; }
        public Nullable<System.DateTime> SUBTIME { get; set; }
        public Nullable<decimal> DELFLAG { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
        public string REMARK { get; set; }
        public string SORT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<R_USERINFO_ACTIONINFO> R_USERINFO_ACTIONINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<R_USERINFO_DEPARTMENT> R_USERINFO_DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<R_USERINFO_ROLEINFO> R_USERINFO_ROLEINFO { get; set; }
    }
}
